### ISSUE TITLE
BUG: Oplossing vinden voor lift motors

### ISSUE THREAD

**Issue by Valentijnvw** [emmaus-6v/2122-6V-Knikkerbaan-groep-3#19]
**Beschrijf de fout**

De 360 servo motor van de lift heeft geen idee hoeveel rondjes hij draait. Voor het omhoog brengen van de lift moet de motor een vaste afstand afleggen, wat niet mogelijk is met deze motor. Bovendien moeten de bovenste en onderste motor precies even snel draaien, zodat de draadjes synchroon met de lift meegaan. De twee motortjes gaan niet even snel als we ze evenveel power geven, omdat de weerstand van het bovenste motortje groter is dan die van de onderste.  Een mogelijke oplossing zou een sensor zijn, maar dit lost het tweede probleem niet op. @cam-emmauscollege heeft u misschien een oplossing hiervoor? Ideaal zou zijn dat we een ander motortje kunnen gebruiken die een vast aantal rotaties kan uitvoeren, zoals bij een Mindstorms motor bijv. het geval is

**Hoe te reproduceren?**

n.v.t.

**Comment by cam-emmauscollege** [comment]
@Valentijnvw @KevinS200412 

Ik lees twee uitdagingen:
1) je wilt de lift een precieze afstand laten bewegen.
2) je wilt dat de twee motortjes precies even snel gaan.

Mij schieten de volgende mogelijkheden te binnen:
- je kunt gebruik maken van een 'encoder'. Hierbij meet je bijv. met een lichtsensor en een schijfje met gaatjes hoeveel 'stapjes' het schijfje (en dus je motor) is gedraaid. Dit zie je vaak in printers enz. Het kost alleen denk ik veel moeite voor jullie om nu nog in jullie ontwerp in te voegen.
- je kunt ook gebruik maken van een stappenmotor. Hiermee kun je in stapjes van bijv. 5 graden aangeven hoeveel stappen er gedraaid moeten worden. Dit vereist wel wat extra electronica voor de aansturing.
- wat betreft de twee motortjes: kun je niet gewoon gebruik maken van 1 motortje en het liftje een beetje zwaarder maken dat die bij het afrollen vanzelf naar beneden schuift?
- je kunt ook nog de 'standaard' beamsensors (die je ook gebruikt om te meten of er een knikker voorbij komt) gebruiken om te 'meten' of de lift helemaal boven of helemaal beneden is. Dan hoef je ook misschien helemaal geen stappenmotor te gebruiken. Je ontwerp wordt dan ook storingsongevoeliger. Je lift gaat dan steeds gewoon door tot de uiteinden.

Dus: 

- heb je echt twee motors nodig? Eén motor vereenvoudigt boel behoorlijk.
- stappen motor kan zeker, maar ik moet even kijken of ik daar alle spullen voor op school heb.
- je kunt ook met sensors meten of de lift boven of beneden is.

Ik ben morgen weer op school. Laten jullie anders vandaag via deze thread nog even jullie gedachten weten?
